[cosmic-ray]
module-path = "src/linear_search.py"
timeout = 20.0
excluded-modules = []
test-command = "PYTHONPATH=src python -m unittest discover -s tests -v"

[cosmic-ray.distributor]
name = "local"
